global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'node'

# Add rule files for alerts
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'kafka-monitoring'
    scrape_interval: 5s
    static_configs:
      - targets: ['128.2.205.128:8765']
  
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['128.2.205.128:9100']