apiVersion: v1
kind: Service
metadata:
  name: movies-load-balancer-service
spec:
  type: NodePort
  selector:
    app: movies-load-balancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
