apiVersion: v1
kind: Service
metadata:
  name: new-movie-model-service
spec:
  type: ClusterIP
  selector:
    app: new-movie-model
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
