# Base image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Install the Python dependencies
RUN pip install --no-cache-dir flask requests

# Copy necessary files
COPY ab_testing_LB.py .

# Expose port 8081 for the Flask app
EXPOSE 8081

# Set the command to run the Flask app
CMD ["python", "ab_testing_LB.py"]